name: Deploy to AWS S3

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Select Deployment Environment"
        options:
          - develop
          - acceptance
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: eu-north-1

      - name: Test AWS Credentials
        run: aws sts get-caller-identity

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "🚀 *${{ github.workflow }}* — ${{ job.status }}",
              "attachments": [
                {
                  "fields": [
                    { "title": "Repo", "value": "${{ github.repository }}", "short": true },
                    { "title": "Branch", "value": "${{ github.ref_name }}", "short": true },
                    { "title": "Author", "value": "${{ github.actor }}", "short": true },
                    { "title": "Commit", "value": "${{ github.event.head_commit.message }}", "short": false }
                  ],
                  "actions": [
                    {
                      "type": "button",
                      "text": "View Run",
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # - name: Configure AWS OIDC Authentication
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     role-to-assume: arn:aws:iam::327816341313:role/github-action-s3-role
      #     aws-region: eu-north-1

      # - name: Deploy to S3
      #   run: |
      #     aws s3 sync ./ s3://${{ vars.S3_BUCKET }} --delete
